### ISSUE TITLE
[Feature]:  xdrlib deprecation and removal in python 3.13

### ISSUE THREAD

**Issue by apop5** [Microsoft/mu_basecore#371]
### Feature Overview

Python 3.11.3 has started to report warnings in regards to the xdrlib.

`
MU_BASECORE\BaseTools\Scripts\BinToPcd.py:16: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13`

This needs to be addressed prior to 3.13 release, and we need to be aware that this will may cause issues supporting older code-bases on newer python tools.

### Solution Overview

BinToPcd.py is the only xdrlib usage, currently. 

### Urgency

Low

### Are you going to implement the feature request?

Someone else needs to implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
Note that I filed a TianoCore bug on 12-09-2022 and Mike Kinney took ownership to fix it.

[Bug 4188 - BinToPcd.py - xdrlib is deprecated in Python 3.11; removal in Python 3.13](https://bugzilla.tianocore.org/show_bug.cgi?id=4188)

**Comment by Javagedes** [comment]
I will take note to monitor this and cherry-pick it when Bug 4188 is resolved.
