### ISSUE TITLE
[Bug]: False negative on Google Tests death test

### ISSUE THREAD

**Issue by kuqin12** [Microsoft/mu_basecore#394]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

When performing death tests, the outcome is inconsistent and could have false negative results.

A detailed unit test usage is outlined in https://github.com/microsoft/mu_basecore/pull/393:

One test would fail silently on an access violation, although that due to a unit test bug. To prevent this, one should always populate the matching string. However, such string is not connected to the existing `DebugLib.h` implementation.

### Expected Behavior

A detailed unit test usage is outlined in https://github.com/microsoft/mu_basecore/pull/393.

But to mitigate the false negative unit tests, we should properly support the asserts for Google Test usage.

### Steps To Reproduce

See https://github.com/microsoft/mu_basecore/pull/393 for full code.

### Build Environment

```markdown
- OS(s): Linux and Windows
- Tool Chain(s): VS2022 and GCC11
- Targets Impacted: x64
```

### Version Information

```text
Top of release/202208
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
- Write up how asserts should be used in unit tests - just print
- Get feedback on the proposal
