### ISSUE TITLE
USB enumeration updates

### ISSUE THREAD

**Issue by kenlautner** [Microsoft/mu_basecore#501]
A couple months ago we made a change that stopped USB enumeration in case a malformed descriptor is found which can be seen [here](https://github.com/microsoft/mu_basecore/commit/714d41b7278194ace70026b5eb8c8bcce68da963).

When ingested into platforms we got several USB enumeration errors due to bad descriptors which led to boot failures.  As a temporary fix we reverted the change but a more robust failure method for malformed descriptors need to exist.  This issue tracks progress for that effort.

**Comment by makubacki** [comment]
The original issue tracking this (#489) was closed when linked to the PRs with the revert. To keep everything together I'm going to continue to use that issue to track a long-term change and close this one as it will also be linked there.
