### ISSUE TITLE
[Feature]: Enhance the FdSizeReportGenerator.py to support multiple FD

### ISSUE THREAD

**Issue by MarcChen46** [Microsoft/mu_basecore#644]
### Feature Overview

It is possible that UEFI will define multiple FDs in FDF file, but currently below implementation from [FdSizeReportGenerator.py](https://github.com/microsoft/mu_basecore/blob/release/202302/BaseTools/Plugin/FdSizeReport/FdSizeReportGenerator.py) only use the first FD it find from the Build Report.

It would be better to enhance it to capture all FDs info first, then each FV can show correct system address with the FV offset + FD base address it belongs to.

    def ParseFdInfo(self):
        CurrentLine = 0
        FoundAll = False
        FoundIt = False
        while(CurrentLine < self.TotalLines) and not FoundAll:
            line = self.ReportFile[CurrentLine]

            if FoundIt:
                tokens = line.strip().split(':')
                if len(tokens) == 2:
                    if(tokens[0].strip().lower() == "fd name"):
                        self.FdName = tokens[1]
                    elif(tokens[0].strip().lower() == 'base address'):
                        self.FdBase=tokens[1]
                        self.FdBaseNum = int(self.FdBase, 0)
                    elif(tokens[0].strip().lower() == 'size'):
                        self.FdSize = tokens[1].split()[0].strip()
                        self.FdSizeNum = int(self.FdSize, 0)
                        FoundAll = True
            elif line.strip().lower() == 'firmware device (fd)':
                FoundIt = True

            CurrentLine = CurrentLine + 1

### Solution Overview

Catch all FD base address in ParseFdInfo method, then calculate the FV's system address by FV offset + FD base address it belongs to.

### Urgency

Medium

### Are you going to implement the feature request?

Someone else needs to implement the feature

### Do you need maintainer feedback?

Maintainer feedback requested

**Comment by Javagedes** [comment]
#647 has been created, which re-writes the report to support multiple FDs as expected.
