### ISSUE TITLE
[Feature]: Crypto On Protocol Support

### ISSUE THREAD

**Issue by apop5** [Microsoft/mu_basecore#871]
### Feature Overview

Crypto On Protocol Support

### Solution Overview

Crypto On Protocol Support

### Urgency

Low

### Are you going to implement the feature request?

I will implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
If I understand correctly, this is referencing [`BaseCryptLibOnProtocolPpi`](https://github.com/tianocore/edk2/tree/master/CryptoPkg/Library/BaseCryptLibOnProtocolPpi) which is already in edk2.

I would like to track some recent changes I made for Standalone MM and Runtime DXE, so I'll reuse this feature unless there was something else to it.
