### ISSUE TITLE
[Feature]: Crypto Elliptic Curve

### ISSUE THREAD

**Issue by apop5** [Microsoft/mu_basecore#872]
### Feature Overview

Crypto Elliptic Curve support

### Solution Overview

Crypto Elliptic Curve support

### Urgency

Low

### Are you going to implement the feature request?

I will implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by spbrogan** [comment]
what does this mean.  We already have some elliptic curve support?

**Comment by apop5** [comment]
This was going to track changes related  https://github.com/microsoft/mu_basecore/commit/33e15727ed

I can close this.
